server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true